name: health_statistics
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  health: ^4.6.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
